In [2]:
import numpy as np
import torch 

In [5]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [6]:
x[1,1]

tensor(3)

In [7]:
x[:, 1]

tensor([1, 3, 5])

In [8]:
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [9]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [10]:
e = torch.arange(10)
e

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
## -1 INFER the right dimension to reshape

e.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
 a = torch.tensor([1, 2, 3])

 b = torch.tensor([4, 5, 6])

In [13]:
a + b

tensor([5, 7, 9])

In [14]:
torch.add(a,b)

tensor([5, 7, 9])

In [15]:
a.mul(b)

tensor([ 4, 10, 18])

In [16]:
a * b

tensor([ 4, 10, 18])

In [17]:
a.mul_(b)
a

tensor([ 4, 10, 18])

In [18]:
 a = torch.tensor([1, 2, 3])

 b = torch.tensor([4, 5, 6])

In [20]:
a * b 

tensor([ 4, 10, 18])

In [21]:
a.dot(b)

tensor(32)

In [28]:
 a = torch.tensor([[1, 2, 3], [0,2,4]])

 b = torch.tensor([[4, 5], [2,4], [1,2]])

In [32]:
a.shape

torch.Size([2, 3])

In [33]:
b.shape

torch.Size([3, 2])

In [35]:
torch.mm(a,b)

tensor([[11, 19],
        [ 8, 16]])

In [36]:
a @ b

tensor([[11, 19],
        [ 8, 16]])

In [43]:
x = torch.arange(6.)
x

tensor([0., 1., 2., 3., 4., 5.])

In [44]:
x.norm()

tensor(7.4162)

In [45]:
x.numel()

6